### PR TITLE
Better Solution for Sum of All Odd Length Subarrays

### PR DESCRIPTION
**Pull request by soham0-0**
Runtime: 0 ms, faster than 100.00%

### CODE REVIEW

**Comment by sadn1ck** [comment]
Can you provide an explanation in the file comments so I can refer to them later :/

**Comment by soham0-0** [comment]
Alright. Will do. ✔️

**Review by sadn1ck — APPROVED** [review]

**Comment by soham0-0** [comment]
@sadn1ck Rather than commenting, I changed the name of your function.

**Comment by soham0-0** [comment]
@sadn1ck There has been some updates in Hacktoberfest so could you please follow these guidelines so that my PRs count?
thank you so much!
[Update link](https://hacktoberfest.digitalocean.com/hacktoberfest-update)

**Pull request merged**
